fix: on linux fall back to native arch if npm_config_arch is not resolved
desktop/dugite pull request #409
Opened 2020-07-09 17:52 UTC by MarshallOfSound

As of https://github.com/desktop/dugite/pull/392 anyone running `dugite` on linux with `npm_config_arch=ia32` set will be unable to use dugite where they previously could.  This at least gets it working again by falling back to `os.arch()` if the `npm_config_arch` binary couldn't be located.

Technically fixes a breaking change

2020-11-05 15:31 UTC, niik commented
@dennisameling would you mind taking a look at this when you have a moment since you authored #392? Thanks!

2020-11-05 15:37 UTC, dennisameling commented
Sure, will have a look in a few hours from now!

2020-11-05 21:50 UTC, dennisameling requested changes
The fallback logic makes sense, but the code contains a bug (just confirmed on WSL2 Linux):

```
> dugite@1.91.3 postinstall /home/dennis/repos/dugite
> node ./script/download-git.js

/home/dennis/repos/dugite/script/config.js:41
  const entry = embeddedGit[key] || embeddedGit[fallbackKey]
                                                ^

ReferenceError: fallbackKey is not defined
    at getConfig (/home/dennis/repos/dugite/script/config.js:41:49)
    at Object.<anonymous> (/home/dennis/repos/dugite/script/download-git.js:11:35)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dugite@1.91.3 postinstall: `node ./script/download-git.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dugite@1.91.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dennis/.npm/_logs/2020-11-05T21_45_38_219Z-debug.log
```

Should suffice to just remove the `embeddedGit[fallbackKey]` altogether, as you're overwriting the regular `key` anyway @MarshallOfSound.

Also, could you briefly explain the scenario for using `npm_config_arch=ia32` on Linux? If the script downloads the 64-bit Git binaries, the package won't work on an `ia32` system, correct? So even though it downloads a valid package, an `ia32`-only machine won't be able to execute Git commands I believe.

2021-01-14 13:10 UTC, 6068 approved these changes

2023-06-25 07:01 UTC, closed without merging