Unset git config safe.directory
desktop/dugite pull request #486
Opened 2022-06-27 13:18 UTC by tidy-dev

Turns out the the actions runner was updated to set the the safe.directory=* which makes are test of the unsafe directory check fail. This PR adds a job step to unset this (like it was before that change) so that our test can properly run tests again that setting.

2022-06-27 13:23 UTC, sergiou87 approved these changes
🤯

2022-06-27 13:25 UTC, sergiou87 commented
Oh it's failing in builds other than macOS x64 😕

2022-06-27 14:45 UTC, niik commented
I think you can just do `git config --global ........ || true` in the workflow file there to have it ignore the exit code and then we can continue debugging what's up with Linux after that. We'll have to do the same debugging that we did for macOS (i.e. look at where if at all the Linux image sets its `safe.directory` as it's evidently not in the global config)

2022-06-27 15:26 UTC, tidy-dev commented on .github/workflows/ci.yml
> +        run: sudo git config --system --unset-all safe.directory || true
Linux sets safe.directory=* at the --system config. I tried simply unsetting it but got "can't lock file" error. When googling seems sudo is what you have to do to modify the --system config.. But if there is a better way I always open. :/

2022-06-28 07:22 UTC, niik requested changes

2022-06-28 07:22 UTC, niik commented on .github/workflows/ci.yml
> +        run: sudo git config --system --unset-all safe.directory || true
It's unfortunate that they put the safe.directory entry in the system config on the Linux images. I think we can still achieve a unified solution to the problem though by leveraging the fact that `safe.directory` is a multi-value config key. See [git-config](https://git-scm.com/docs/git-config#:~:text=This%20is%20a%20multi%2Dvalued%20setting%2C%20i.e.%20you%20can%20add%20more%20than%20one%20directory%20via%20git%20config%20%2D%2Dadd.%20To%20reset%20the%20list%20of%20safe%20directories%20(e.g.%20to%20override%20any%20such%20directories%20specified%20in%20the%20system%20config)%2C%20add%20a%20safe.directory%20entry%20with%20an%20empty%20value.)

> This is a multi-valued setting, i.e. you can add more than one directory via git config --add. To reset the list of safe directories (e.g. to override any such directories specified in the system config), add a safe.directory entry with an empty value.

```suggestion
      - name: Reset safe.directory
        run: git config --global --add safe.directory ""
        shell: bash
```

The `shell: bash` part is needed to not have to do special escaping for empty arguments just for Windows' Powershell.

2022-06-29 12:26 UTC, niik approved these changes
Happy to put this problem to rest 😄

2022-06-29 12:32 UTC, merged

2022-07-22 23:04 UTC, Tommy46Godfrey2918 reviewed
@sergiou87